= bespoke-blackout
Dan Allen <https://github.com/mojavelinux>
// Settings:
:idprefix:
:idseparator: -
:experimental:
ifdef::env-github[:badges:]
// Variables:
:release-version: v1.0.0
// URIs:
:uri-raw-file-base: https://raw.githubusercontent.com/opendevise/bespoke-blackout/{release-version}

ifdef::badges[]
image:https://img.shields.io/npm/v/bespoke-blackout.svg[npm package, link=https://www.npmjs.com/package/bespoke-blackout]
image:https://img.shields.io/travis/opendevise/bespoke-blackout/master.svg[Build Status (Travis CI), link=https://travis-ci.org/opendevise/bespoke-blackout]
endif::[]

Toggles blackout mode when either the kbd:[b] or kbd:[.] key is pressed in a http://markdalgleish.com/projects/bespoke.js[Bespoke.js] presentation.
Give your audience a breather.

TIP: If you have form elements in your slides, use the https://github.com/markdalgleish/bespoke-forms[bespoke-forms] plugin to prevent pause mode toggle from being triggered while typing.

== Example

http://opendevise.github.io/bespoke-blackout[View the demo] online.

This repository includes a demo folder the shows this plugin in action.
To view it locally, you first need to clone this repository:

 $ git clone https://github.com/opendevise/bespoke-blackout && cd bespoke-blackout

Next, install the dependencies inside the project folder using npm:

 $ npm install

Finally, visit the file [path]_demo/index.html_ in your browser to see the plugin in action.

== Download

Download the {uri-raw-file-base}/dist/bespoke-blackout.min.js[production version] or the {uri-raw-file-base}/dist/bespoke-blackout.js[development version], or use a package manager.

=== npm

 $ npm install bespoke-blackout

=== Bower

 $ bower install bespoke-blackout

== Usage

This plugin is shipped in a https://github.com/umdjs/umd[UMD format], meaning it is available as a CommonJS/AMD module or as a browser global.

For example, when using CommonJS modules:

```js
var bespoke = require('bespoke'),
  blackout = require('bespoke-blackout');

bespoke.from('.deck', [
  blackout()
]);
```

When using browser globals:

```js
bespoke.from('.deck', [
  bespoke.plugins.blackout()
]);
```

=== Behavior

This plugin activates the following keybindings:

[width=50%]
|===
|Function |Shortcut(s)

|Blackout
|kbd:[b], kbd:[.]
|===

NOTE: These keybindings are not triggered if a modifier key (e.g., kbd:[Ctrl]) is pressed.

== License

http://en.wikipedia.org/wiki/MIT_License[MIT License]
